Fixed deprecations this.property-fallback, with, and positional linkt…
ember-learn/ember-cli-addon-docs pull request #831
Opened 2021-05-12 21:53 UTC by bgantzler

…o parms

2021-05-21 13:46 UTC, rwwagner90 requested changes
Thanks for the PR! Was just about to address this myself.

2021-05-21 13:46 UTC, rwwagner90 commented on tests/acceptance/sandbox/api/guides-test.js
> +debugger;
```suggestion
```

2021-05-21 13:46 UTC, rwwagner90 commented on index.js
> +
```suggestion
```

Was this needed for something?

2021-05-21 13:55 UTC, rwwagner90 approved these changes

2021-05-21 15:21 UTC, merged

2021-05-21 21:38 UTC, cah-briangantzler commented
OMG, must have been doing too many things. Sorry for leaving the debugger and developing addon in. I know better :(

2021-05-22 16:13 UTC, rwwagner90 commented
No worries @cah-briangantzler! I really appreciate the help 😃